name: Docker CI Pipeline

on:
  push:
    branches:
      - main


env:
  IMAGE_NAME: cicd-demo
  IMAGE_TAG: latest

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker save $IMAGE_NAME:$IMAGE_TAG -o image.tar
          echo "Docker image built and saved."

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: image-tar
          path: image.tar
          retention-days: 1

  unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar
          path: .

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load Docker Image
        run: docker load -i image.tar

      - name: Run Unit Tests
        run: |
          echo "Running application unit tests..."
          docker run --rm $IMAGE_NAME:$IMAGE_TAG pytest -v test/test_app.py
          echo "Unit tests completed successfully."

  lint_test:
    name: Run Lint Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar
          path: .
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load Docker Image
        run: docker load -i image.tar

      - name: Run Lint Tests
        run: |
          echo "Running linting tests..."
          docker run --rm $IMAGE_NAME:$IMAGE_TAG pytest -v test/test_lint.py
          echo "Linting tests completed successfully."

  docker_push:
    name: Push Docker Image
    runs-on: ubuntu-latest
    needs: [unit_test, lint_test]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: image-tar
          path: .
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Load Docker Image
        run: docker load -i image.tar

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          echo "Tagging and pushing Docker image..."
          docker tag $IMAGE_NAME:$IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
          echo "Docker image pushed successfully."
